package com.stockshield.service;
import com.stockshield.entity.*; import com.stockshield.repository.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*; import java.util.concurrent.*;
@Service public class OrderService {private final OrderRepository orders; private final ProductRepository products; private final OrderEventRepository events; private final DeadLetterRepository dlq; private final IdempotencyRepository idem; private final EventPublisher publisher; private final ExecutorService executor; private final Random random=new Random(); private static final int MAX_RETRIES=3;
public OrderService(OrderRepository o,ProductRepository p,OrderEventRepository e,DeadLetterRepository d,IdempotencyRepository i,EventPublisher pub,ExecutorService ex){orders=o;products=p;events=e;dlq=d;idem=i;publisher=pub;executor=ex;}
@Transactional public Order createAndSubmit(Long productId,int qty,String key){var existing=idem.findByKeyValue(key); if(existing.isPresent()) return orders.findById(existing.get().getOrderId()).orElseThrow(); Product p=products.findById(productId).orElseThrow(); Order o=new Order();o.setOrderCode("ORD-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());o.setProduct(p);o.setQuantity(qty);o.setStatus(Order.Status.CREATED);o.setRetryCount(0);o.setIdempotencyKey(key);o=orders.save(o); try{idem.save(new IdempotencyKey(key,o.getId()));}catch(DataIntegrityViolationException ex){return idem.findByKeyValue(key).map(x->orders.findById(x.getOrderId()).orElse(o)).orElse(o);} Long id=o.getId(); executor.submit(()->process(id)); return o; }
@Transactional public void process(Long id){Order o=orders.findById(id).orElse(null);if(o==null||o.getStatus()==Order.Status.SUCCESS||o.getStatus()==Order.Status.DLQ)return;o.setStatus(Order.Status.PROCESSING);events.save(new OrderEvent(id,"PROCESSING","Order entered processing"));publish(o); try{ if(random.nextInt(100)<3) throw new RuntimeException("Simulated transient processing failure"); Product p=products.findLockedById(o.getProduct().getId()).orElseThrow(); if(p.getInventory()<o.getQuantity()){o.setStatus(Order.Status.OUT_OF_STOCK);events.save(new OrderEvent(id,"OUT_OF_STOCK","Insufficient inventory"));}else{p.setInventory(p.getInventory()-o.getQuantity());o.setStatus(Order.Status.SUCCESS);events.save(new OrderEvent(id,"SUCCESS","Inventory reserved and order completed"));}orders.save(o);publish(o);}catch(Exception ex){retryOrDlq(o,ex);}}
@Transactional public void retryOrDlq(Order o,Exception ex){int next=o.getRetryCount()+1;o.setRetryCount(next);if(next<=MAX_RETRIES){o.setStatus(Order.Status.RETRYING);events.save(new OrderEvent(o.getId(),"RETRYING","Retry "+next+"/"+MAX_RETRIES));orders.save(o);publish(o);long delay=(long)Math.pow(2,next)*100L;executor.submit(()->{try{Thread.sleep(delay);}catch(InterruptedException ignored){Thread.currentThread().interrupt();}process(o.getId());});}else{o.setStatus(Order.Status.DLQ);orders.save(o);dlq.save(new DeadLetterOrder(o.getId(),ex.getMessage()==null?"Permanent processing failure":ex.getMessage()));events.save(new OrderEvent(o.getId(),"DLQ","Retry exhaustion; moved to DLQ"));publish(o);}}
@Transactional public void reprocessDlq(Long dlqId){DeadLetterOrder d=dlq.findById(dlqId).orElseThrow();if(d.isReprocessed())return;Order o=orders.findById(d.getOrderId()).orElseThrow();d.setReprocessed(true);dlq.save(d);o.setRetryCount(0);o.setStatus(Order.Status.CREATED);orders.save(o);executor.submit(()->process(o.getId()));}
public List<Order> recent(){return orders.findTop50ByOrderByCreatedAtDesc();} public long count(Order.Status s){return orders.countByStatus(s);} public List<DeadLetterOrder> deadLetters(){return dlq.findByReprocessedFalseOrderByCreatedAtDesc();} public void publish(Order o){publisher.publish(Map.of("orderCode",o.getOrderCode(),"status",o.getStatus().name(),"retryCount",o.getRetryCount(),"inventory",o.getProduct().getInventory()));}}
